# render.yaml
services:
  - type: web
    name: bapenda-jawa-tengah
    env: php
    plan: free  # sesuaikan dengan plan Render
    branch: main  # branch repo kamu
    buildCommand: |
      apt-get update && apt-get install -y php-pgsql
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      # php artisan migrate --force  # uncomment kalau mau auto migrate
    startCommand: |
      php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:ABQXg/QwX21/4pOpncFwQwTJHpm42ccFSE6/0fUH210=
      - key: APP_URL
        value: https://bapenda-jawa-tengah.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d49n64vpm1nc73dg1qcg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: '5432'
      - key: DB_DATABASE
        value: bapenda_db
      - key: DB_USERNAME
        value: bapenda_user
      - key: DB_PASSWORD
        value: Qqvopby4NoOma3Y4MI73pcLI9DWBmgl3
      - key: PGSSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
